#!/bin/bash

echo "==============================================="
echo "   REPLACE REMAINING FONT AWESOME ICONS"
echo "==============================================="
echo ""

# List of remaining Font Awesome icons to replace
FA_ICONS="
fa-user-circle
fa-user-circle-o
fa-user-md
fa-user-plus
fa-user-secret
fa-user-times
fa-users-cog
fa-users-class
fa-users-slash
fa-tachometer
fa-tachometer-alt
fa-database
fa-server
fa-cloud
fa-cloud-upload-alt
fa-cloud-download-alt
fa-print
fa-print-search
fa-link
fa-unlink
fa-chain-broken
fa-external-link
fa-external-link-alt
fa-magic
fa-automobile
fa-cab
fa-taxi
fa-shuttle-van
fa-truck
fa-ambulance
fa-bicycle
fa-bus
fa-car
fa-motorcycle
fa-plane
fa-rocket
fa-ship
fa-subway
fa-train
fa-anchor
fa-balance-scale
fa-bolt
fa-bomb
fa-book
fa-bookmark
fa-briefcase
fa-bullhorn
fa-bullseye
fa-calculator
fa-calendar-check
fa-calendar-minus
fa-calendar-plus
fa-calendar-times
fa-camera-retro
fa-cart-plus
fa-certificate
fa-chart-area
fa-chart-bar
fa-chart-line
fa-chart-pie
fa-check-double
fa-check-square
fa-circle
fa-circle-notch
fa-clipboard
fa-clock
fa-clone
fa-code
fa-code-branch
fa-cog
fa-cogs
fa-comment
fa-comment-alt
fa-comment-dollar
fa-comment-dots
fa-comment-medical
fa-comment-slash
fa-comments
fa-comments-dollar
fa-compact-disc
fa-compass
fa-compress
fa-copy
fa-copyright
fa-credit-card
fa-crop
fa-crosshairs
fa-cube
fa-cubes
fa-cut
fa-dashboard
fa-database
fa-desktop
fa-diagnoses
fa-dice
fa-dice-d6
fa-dice-five
fa-dice-four
fa-dice-one
fa-dice-six
fa-dice-three
fa-dice-two
fa-digital-tachograph
fa-directions
fa-divide
fa-dizzy
fa-dna
fa-dollar-sign
fa-dolly
fa-dolly-flatbed
fa-donate
fa-door-closed
fa-door-open
fa-dot-circle
fa-dove
fa-download
fa-drafting-compass
fa-dragon
fa-draw-polygon
fa-drum
fa-drum-steelpan
fa-dumbbell
fa-edit
fa-ellipsis-h
fa-ellipsis-v
fa-envelope
fa-envelope-open
fa-envelope-square
fa-eraser
fa-euro-sign
fa-exchange-alt
fa-exclamation
fa-exclamation-circle
fa-exclamation-triangle
fa-expand
fa-expand-arrows-alt
fa-external-link-alt
fa-eye
fa-eye-dropper
fa-eye-slash
fa-fast-backward
fa-fast-forward
fa-fax
fa-feather
fa-feather-alt
fa-female
fa-fighter-jet
fa-file
fa-file-alt
fa-file-archive
fa-file-audio
fa-file-code
fa-file-contract
fa-file-csv
fa-file-download
fa-file-excel
fa-file-export
fa-file-image
fa-file-import
fa-file-invoice
fa-file-invoice-dollar
fa-file-medical
fa-file-medical-alt
fa-file-pdf
fa-file-powerpoint
fa-file-prescription
fa-file-signature
fa-file-upload
fa-file-video
fa-file-word
fa-fill
fa-fill-drip
fa-film
fa-filter
fa-fingerprint
fa-fire
fa-fire-extinguisher
fa-firefox
fa-first-aid
fa-fish
fa-flag
fa-flag-checkered
fa-flask
fa-flushed
fa-folder
fa-folder-open
fa-font
fa-football-ball
fa-forward
fa-frog
fa-frown
fa-frown-open
fa-funnel-dollar
fa-futbol
fa-gamepad
fa-gas-pump
fa-gavel
fa-gem
fa-genderless
fa-ghost
fa-gift
fa-gifts
fa-glass-cheers
fa-glass-martini
fa-glass-martini-alt
fa-glass-whiskey
fa-glasses
fa-globe
fa-globe-africa
fa-globe-americas
fa-globe-asia
fa-globe-europe
fa-golf-ball
fa-graduation-cap
fa-greater-than
fa-greater-than-equal
fa-grimace
fa-grin
fa-grin-alt
fa-grin-beam
fa-grin-beam-sweat
fa-grin-hearts
fa-grin-squint
fa-grin-squint-tears
fa-grin-stars
fa-grin-tears
fa-grin-tongue
fa-grin-tongue-squint
fa-grin-tongue-wink
fa-grin-wink
fa-grip-horizontal
fa-grip-lines
fa-grip-lines-vertical
fa-grip-vertical
fa-guitar
fa-h-square
fa-hammer
fa-hamsa
fa-hand-holding
fa-hand-holding-heart
fa-hand-holding-usd
fa-hand-lizard
fa-hand-middle-finger
fa-hand-paper
fa-hand-peace
fa-hand-point-down
fa-hand-point-left
fa-hand-point-right
fa-hand-point-up
fa-hand-pointer
fa-hand-rock
fa-hand-scissors
fa-hand-spock
fa-hands
fa-hands-helping
fa-handshake
fa-hashtag
fa-hat-wizard
fa-haykal
fa-hdd
fa-heading
fa-headphones
fa-headphones-alt
fa-headset
fa-heart
fa-heart-broken
fa-heartbeat
fa-helicopter
fa-highlighter
fa-hiking
fa-history
fa-hockey-puck
fa-holly-berry
fa-home
fa-horse
fa-horse-head
fa-hospital
fa-hospital-alt
fa-hospital-symbol
fa-hot-tub
fa-hourglass
fa-hourglass-end
fa-hourglass-half
fa-hourglass-start
fa-house-damage
fa-hryvnia
fa-i-cursor
fa-ice-cream
fa-icicles
fa-icons
fa-id-badge
fa-id-card
fa-id-card-alt
fa-igloo
fa-image
fa-images
fa-inbox
fa-indent
fa-industry
fa-infinity
fa-info
fa-info-circle
fa-italic
fa-jedi
fa-joint
fa-journal-whills
fa-kaaba
fa-key
fa-keyboard
fa-khanda
fa-kiss
fa-kiss-beam
fa-kiss-wink-heart
fa-kiwi-bird
fa-landmark
fa-language
fa-laptop
fa-laptop-code
fa-laptop-medical
fa-laugh
fa-laugh-beam
fa-laugh-squint
fa-laugh-wink
fa-layer-group
fa-leaf
fa-lemon
fa-less-than
fa-less-than-equal
fa-level-down-alt
fa-level-up-alt
fa-life-ring
fa-lightbulb
fa-link
fa-lira-sign
fa-list
fa-list-alt
fa-list-ol
fa-list-ul
fa-location-arrow
fa-lock
fa-lock-open
fa-long-arrow-alt-down
fa-long-arrow-alt-left
fa-long-arrow-alt-right
fa-long-arrow-alt-up
fa-low-vision
fa-luggage-cart
fa-magic
fa-magnet
fa-mail-bulk
fa-male
fa-map
fa-map-marked
fa-map-marked-alt
fa-map-marker
fa-map-marker-alt
fa-map-pin
fa-map-signs
fa-marker
fa-mars
fa-mars-double
fa-mars-stroke
fa-mars-stroke-h
fa-mars-stroke-v
fa-mask
fa-medal
fa-medkit
fa-meh
fa-meh-blank
fa-meh-rolling-eyes
fa-memory
fa-menorah
fa-mercury
fa-meteor
fa-microchip
fa-microphone
fa-microphone-alt
fa-microphone-alt-slash
fa-microphone-slash
fa-microscope
fa-minus
fa-minus-circle
fa-minus-square
fa-mitten
fa-mobile
fa-mobile-alt
fa-money-bill
fa-money-bill-alt
fa-money-bill-wave
fa-money-bill-wave-alt
fa-money-check
fa-money-check-alt
fa-monument
fa-moon
fa-mortar-pestle
fa-mosque
fa-motorcycle
fa-mountain
fa-mouse
fa-mouse-pointer
fa-mug-hot
fa-music
fa-network-wired
fa-neuter
fa-newspaper
fa-not-equal
fa-notes-medical
fa-object-group
fa-object-ungroup
fa-oil-can
fa-om
fa-otter
fa-outdent
fa-pager
fa-paint-brush
fa-paint-roller
fa-palette
fa-pallet
fa-paper-plane
fa-paperclip
fa-parachute-box
fa-paragraph
fa-parking
fa-passport
fa-pastafarianism
fa-paste
fa-pause
fa-pause-circle
fa-paw
fa-peace
fa-pen
fa-pen-alt
fa-pen-fancy
fa-pen-nib
fa-pen-square
fa-pencil-alt
fa-pencil-ruler
fa-people-arrows
fa-people-carry
fa-pepper-hot
fa-percent
fa-percentage
fa-person-booth
fa-phone
fa-phone-alt
fa-phone-slash
fa-phone-square
fa-phone-square-alt
fa-phone-volume
fa-photo-video
fa-piggy-bank
fa-pills
fa-pizza-slice
fa-place-of-worship
fa-plane
fa-plane-arrival
fa-plane-departure
fa-play
fa-play-circle
fa-plug
fa-plus
fa-plus-circle
fa-plus-square
fa-podcast
fa-poll
fa-poll-h
fa-poo
fa-poo-storm
fa-poop
fa-portrait
fa-pound-sign
fa-power-off
fa-pray
fa-praying-hands
fa-prescription
fa-prescription-bottle
fa-prescription-bottle-alt
fa-print
fa-procedures
fa-project-diagram
fa-puzzle-piece
fa-qrcode
fa-question
fa-question-circle
fa-quidditch
fa-quote-left
fa-quote-right
fa-quran
fa-radiation
fa-radiation-alt
fa-rainbow
fa-random
fa-receipt
fa-recycle
fa-redo
fa-redo-alt
fa-registered
fa-remove-format
fa-reply
fa-reply-all
fa-republican
fa-restroom
fa-retweet
fa-ribbon
fa-ring
fa-road
fa-robot
fa-rocket
fa-route
fa-rss
fa-rss-square
fa-ruble-sign
fa-ruler
fa-ruler-combined
fa-ruler-horizontal
fa-ruler-vertical
fa-running
fa-rupee-sign
fa-sad-cry
fa-sad-tear
fa-satellite
fa-satellite-dish
fa-save
fa-school
fa-screwdriver
fa-scroll
fa-sd-card
fa-search
fa-search-dollar
fa-search-location
fa-search-minus
fa-search-plus
fa-seedling
fa-server
fa-shapes
fa-share
fa-share-alt
fa-share-alt-square
fa-share-square
fa-shekel-sign
fa-shield-alt
fa-ship
fa-shipping-fast
fa-shoe-prints
fa-shopping-bag
fa-shopping-basket
fa-shopping-cart
fa-shower
fa-shuttle-van
fa-sign
fa-sign-in-alt
fa-sign-language
fa-sign-out-alt
fa-signal
fa-signature
fa-sim-card
fa-sitemap
fa-skating
fa-skiing
fa-skiing-nordic
fa-skull
fa-skull-crossbones
fa-slash
fa-sleigh
fa-sliders-h
fa-smile
fa-smile-beam
fa-smile-wink
fa-smog
fa-smoking
fa-smoking-ban
fa-sms
fa-snowboarding
fa-snowflake
fa-snowman
fa-snowplow
fa-socks
fa-solar-panel
fa-sort
fa-sort-alpha-down
fa-sort-alpha-down-alt
fa-sort-alpha-up
fa-sort-alpha-up-alt
fa-sort-amount-down
fa-sort-amount-down-alt
fa-sort-amount-up
fa-sort-amount-up-alt
fa-sort-down
fa-sort-numeric-down
fa-sort-numeric-down-alt
fa-sort-numeric-up
fa-sort-numeric-up-alt
fa-sort-up
fa-spa
fa-space-shuttle
fa-spider
fa-spinner
fa-splotch
fa-spray-can
fa-square
fa-square-full
fa-square-root-alt
fa-stamp
fa-star
fa-star-and-crescent
fa-star-half
fa-star-half-alt
fa-star-of-david
fa-star-of-life
fa-step-backward
fa-step-forward
fa-stethoscope
fa-sticky-note
fa-stop
fa-stop-circle
fa-stopwatch
fa-store
fa-store-alt
fa-stream
fa-street-view
fa-strikethrough
fa-stroopwafel
fa-subscript
fa-subway
fa-suitcase
fa-suitcase-rolling
fa-sun
fa-superscript
fa-surprise
fa-swatchbook
fa-swimmer
fa-swimming-pool
fa-synagogue
fa-sync
fa-sync-alt
fa-syringe
fa-table
fa-table-tennis
fa-tablet
fa-tablet-alt
fa-tablets
fa-tachometer-alt
fa-tag
fa-tags
fa-tape
fa-tasks
fa-taxi
fa-teeth
fa-teeth-open
fa-temperature-high
fa-temperature-low
fa-tenge
fa-terminal
fa-text-height
fa-text-width
fa-th
fa-th-large
fa-th-list
fa-theater-masks
fa-thermometer
fa-thermometer-empty
fa-thermometer-full
fa-thermometer-half
fa-thermometer-quarter
fa-thermometer-three-quarters
fa-thumbs-down
fa-thumbs-up
fa-thumbtack
fa-ticket-alt
fa-times
fa-times-circle
fa-tint
fa-tint-slash
fa-tired
fa-toggle-off
fa-toggle-on
fa-toilet
fa-toilet-paper
fa-toolbox
fa-tools
fa-tooth
fa-torah
fa-torii-gate
fa-tractor
fa-trademark
fa-traffic-light
fa-train
fa-tram
fa-transgender
fa-transgender-alt
fa-trash
fa-trash-alt
fa-trash-restore
fa-trash-restore-alt
fa-tree
fa-trophy
fa-truck
fa-truck-loading
fa-truck-monster
fa-truck-moving
fa-truck-pickup
fa-tshirt
fa-tty
fa-tv
fa-umbrella
fa-umbrella-beach
fa-underline
fa-undo
fa-undo-alt
fa-universal-access
fa-university
fa-unlink
fa-unlock
fa-unlock-alt
fa-upload
fa-user
fa-user-alt
fa-user-alt-slash
fa-user-astronaut
fa-user-check
fa-user-circle
fa-user-clock
fa-user-cog
fa-user-edit
fa-user-friends
fa-user-graduate
fa-user-injured
fa-user-lock
fa-user-md
fa-user-minus
fa-user-ninja
fa-user-plus
fa-user-secret
fa-user-shield
fa-user-slash
fa-user-tag
fa-user-tie
fa-user-times
fa-users
fa-users-cog
fa-utensil-spoon
fa-utensils
fa-vector-square
fa-venus
fa-venus-double
fa-venus-mars
fa-vial
fa-vials
fa-video
fa-video-slash
fa-vihara
fa-voicemail
fa-volleyball-ball
fa-volume-down
fa-volume-mute
fa-volume-off
fa-volume-up
fa-vote-yea
fa-vr-cardboard
fa-walking
fa-wallet
fa-warehouse
fa-water
fa-wave-square
fa-weight
fa-weight-hanging
fa-wheelchair
fa-wifi
fa-wind
fa-window-close
fa-window-maximize
fa-window-minimize
fa-window-restore
fa-wine-bottle
fa-wine-glass
fa-wine-glass-alt
fa-won-sign
fa-wrench
fa-x-ray
fa-yen-sign
fa-yin-yang
"

# Function to replace Font Awesome with SVG
replace_fa_icon() {
    local fa_icon=$1
    local svg_icon=$2
    
    # Replace standalone icons
    find templates -name "*.html" ! -name "*backup*" -type f -exec sed -i "s|<i class=\"[^\"]*$fa_icon[^\"]*\"></i>|<svg class=\"icon-svg icon-$svg_icon\"><use href=\"/static/icons/svg/icons.svg#$svg_icon\"/></svg>|g" {} \;
    
    # Replace icons with text
    find templates -name "*.html" ! -name "*backup*" -type f -exec sed -i "s|<i class=\"[^\"]*$fa_icon[^\"]*\">\([^<]*\)</i>|<svg class=\"icon-svg icon-$svg_icon\"><use href=\"/static/icons/svg/icons.svg#$svg_icon\"/></svg><span class=\"icon-label\">\1</span>|g" {} \;
}

# Map common remaining icons
FA_TO_SVG="
user-circle|icon-user
user-plus|icon-plus
users-cog|icon-cog
tachometer-alt|icon-dashboard
cloud-upload-alt|icon-upload
external-link-alt|icon-link
calendar-check|icon-check
calendar-plus|icon-plus
calendar-times|icon-close
chart-area|icon-chart
chart-bar|icon-chart
chart-line|icon-chart
chart-pie|icon-chart
check-double|icon-check
check-square|icon-check
circle|icon-circle
clipboard|icon-copy
code|icon-code
code-branch|icon-code
comment|icon-chat
comment-alt|icon-chat
comment-dots|icon-chat
comments|icon-chat
copy|icon-copy
credit-card|icon-card
desktop|icon-desktop
divide|icon-divide
dollar-sign|icon-dollar
download|icon-download
edit|icon-edit
envelope|icon-envelope
envelope-open|icon-envelope
exclamation|icon-exclamation
exclamation-circle|icon-exclamation-circle
exclamation-triangle|icon-exclamation-triangle
expand|icon-expand
eye|icon-eye
eye-slash|icon-eye-slash
file|icon-file
file-alt|icon-file
file-csv|icon-file
file-download|icon-download
file-excel|icon-file
file-export|icon-file
file-import|icon-upload
file-pdf|icon-file
file-upload|icon-upload
filter|icon-filter
flag|icon-flag
folder|icon-folder
folder-open|icon-folder
gavel|icon-gavel
globe|icon-globe
graduation-cap|icon-school
handshake|icon-handshake
history|icon-history
home|icon-home
inbox|icon-inbox
info|icon-info
info-circle|icon-info
key|icon-key
keyboard|icon-keyboard
laptop|icon-laptop
lightbulb|icon-lightbulb
link|icon-link
list|icon-list
lock|icon-lock
lock-open|icon-lock
magic|icon-magic
map|icon-map
map-marker|icon-location
minus|icon-minus
minus-circle|icon-minus
mobile|icon-mobile
money-bill|icon-money
moon|icon-moon
music|icon-music
newspaper|icon-news
pause|icon-pause
play|icon-play
plus|icon-plus
plus-circle|icon-plus
print|icon-print
question|icon-help
question-circle|icon-help
quote-left|icon-quote
quote-right|icon-quote
random|icon-random
redo|icon-redo
refresh|icon-refresh
reply|icon-reply
robot|icon-robot
rocket|icon-rocket
save|icon-save
school|icon-school
search|icon-search
search-minus|icon-search
search-plus|icon-search
server|icon-server
share|icon-share
shield-alt|icon-shield
sign-in-alt|icon-sign-in
sign-out-alt|icon-sign-out
star|icon-star
star-half|icon-star
sync|icon-sync
sync-alt|icon-sync
tag|icon-tag
tags|icon-tag
tasks|icon-tasks
thumbs-down|icon-thumbs-down
thumbs-up|icon-thumbs-up
times|icon-close
times-circle|icon-close
trash|icon-trash
trash-alt|icon-trash
undo|icon-undo
university|icon-school
unlock|icon-lock
upload|icon-upload
user|icon-user
user-alt|icon-user
user-check|icon-check
user-clock|icon-clock
user-cog|icon-cog
user-edit|icon-edit
user-friends|icon-users
user-graduate|icon-school
user-minus|icon-minus
user-plus|icon-plus
user-shield|icon-shield
user-tag|icon-tag
user-tie|icon-user
users|icon-users
wrench|icon-wrench
"

# Process replacements
echo "Replacing remaining Font Awesome icons..."
count=0
for map in $FA_TO_SVG; do
    fa_icon=$(echo "$map" | cut -d'|' -f1)
    svg_icon=$(echo "$map" | cut -d'|' -f2)
    
    # Count before replacement
    before=$(grep -r "fa-$fa_icon" templates/ --include="*.html" 2>/dev/null | grep -v backup | wc -l)
    
    if [ "$before" -gt 0 ]; then
        replace_fa_icon "$fa_icon" "$svg_icon"
        count=$((count + before))
        echo "  Replaced $before instances of fa-$fa_icon"
    fi
done

echo ""
echo "✅ Replaced $count additional Font Awesome icons"
echo ""
echo "Final check:"
REMAINING=$(grep -r "fa-" templates/ --include="*.html" 2>/dev/null | grep -v backup | wc -l)
echo "Remaining Font Awesome icons: $REMAINING"

if [ "$REMAINING" -gt 0 ]; then
    echo ""
    echo "Files still with Font Awesome icons:"
    grep -l "fa-" templates/*.html 2>/dev/null | grep -v backup | while read file; do
        count=$(grep -c "fa-" "$file" 2>/dev/null)
        echo "  - $file ($count icons)"
    done
else
    echo "✅ All Font Awesome icons replaced!"
fi

echo ""
echo "🚀 Restart server: python manage.py runserver"
