# Generated by Django 6.0.6 on 2026-06-29 18:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('ATTENDANCE', 'Attendance Offenses'), ('ACADEMIC', 'Academic Offenses'), ('UNIFORM', 'Uniform & Grooming Offenses'), ('CLASSROOM', 'Classroom Misconduct'), ('DISRESPECT', 'Disrespect & Insubordination'), ('BULLYING', 'Bullying & Harassment'), ('FIGHTING', 'Fighting & Violence'), ('THEFT', 'Theft & Dishonesty'), ('PROPERTY', 'School Property Offenses'), ('TECHNOLOGY', 'Technology & Phone Misuse'), ('SUBSTANCE', 'Substance Abuse Offenses'), ('SEXUAL', 'Sexual Misconduct'), ('RELATIONSHIP', 'Relationship & Coupling Offenses'), ('SECURITY', 'School Security Offenses'), ('MASS_INDISCIPLINE', 'Mass Indiscipline'), ('HEALTH_SAFETY', 'Health & Safety Violations'), ('COMMUNITY', 'Community & Social Misconduct'), ('EXAM', 'Examination & Assessment Offenses'), ('LEADERSHIP', 'Leadership & Prefect Misconduct'), ('TRANSPORT', 'Transport & Travel Offenses'), ('ENVIRONMENT', 'Environmental & Sanitation Offenses'), ('CRIMINAL', 'Criminal & Legal Offenses')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('default_rating', models.CharField(choices=[('VERY_MINOR', 'Very Minor'), ('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SERIOUS', 'Serious'), ('VERY_SERIOUS', 'Very Serious')], default='MODERATE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('risk_weight', models.PositiveSmallIntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], default=1, help_text='Weight multiplier for risk calculation (1-5)')),
                ('severity_level', models.PositiveSmallIntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], default=3, help_text='Severity level of the offense')),
            ],
            options={
                'verbose_name_plural': 'Discipline Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='School name', max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('motto', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school/')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('current_year', models.IntegerField(default=2026)),
                ('terms_per_year', models.IntegerField(choices=[(1, '1 Term'), (2, '2 Terms'), (3, '3 Terms'), (4, '4 Terms')], default=3)),
                ('allow_teacher_registration', models.BooleanField(default=True)),
                ('require_teacher_approval', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'School Settings',
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.school')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='core.school')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('form', models.CharField(choices=[('Form 1', 'Form 1'), ('Form 2', 'Form 2'), ('Form 3', 'Form 3'), ('Form 4', 'Form 4'), ('Form 5', 'Form 5'), ('Form 6', 'Form 6'), ('Form 7', 'Form 7'), ('Form 8', 'Form 8'), ('Form 9', 'Form 9'), ('Form 10', 'Form 10')], max_length=10)),
                ('year', models.IntegerField(default=2026)),
                ('optional_notes', models.TextField(blank=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='student_pics/')),
                ('risk_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_level', models.CharField(choices=[('GOOD', 'Good'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, default='GOOD', max_length=20)),
                ('ai_risk_factors', models.JSONField(blank=True, default=dict, null=True)),
                ('ai_last_analysis', models.DateTimeField(blank=True, null=True)),
                ('intervention_count', models.PositiveIntegerField(default=0)),
                ('last_incident_date', models.DateTimeField(blank=True, null=True)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('academic_status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRANSFERRED', 'Transferred'), ('DROPPED', 'Dropped Out'), ('GRADUATED', 'Graduated')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_students', to=settings.AUTH_USER_MODEL)),
                ('grade_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.gradelevel')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.stream')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('critical', 'Critical Alert'), ('warning', 'Warning'), ('info', 'Information'), ('success', 'Success')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_read', models.BooleanField(default=False)),
                ('target_users', models.ManyToManyField(related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisciplineReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(editable=False, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('rating', models.CharField(choices=[('VERY_MINOR', 'Very Minor'), ('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SERIOUS', 'Serious'), ('VERY_SERIOUS', 'Very Serious')], default='MODERATE', max_length=20)),
                ('points', models.IntegerField(default=10)),
                ('reported_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='core.disciplinecategory')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='core.student')),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_form', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=False)),
                ('has_chosen_stream', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspension_reason', models.TextField(blank=True, null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_teachers', to=settings.AUTH_USER_MODEL)),
                ('assigned_stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stream')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('new_password', models.CharField(blank=True, max_length=128, null=True)),
                ('notes', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_resets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status'], name='core_passwo_status_76cc29_idx'), models.Index(fields=['requested_at'], name='core_passwo_request_0d688c_idx')],
            },
        ),
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('term_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_current', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='core.school')),
            ],
            options={
                'ordering': ['-year', '-term_number'],
                'unique_together': {('school', 'year', 'term_number')},
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['admission_number'], name='core_studen_admissi_102036_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['name'], name='core_studen_name_a58b91_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['stream', 'form'], name='core_studen_stream__e73239_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['risk_score'], name='core_studen_risk_sc_af1aee_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['risk_level'], name='core_studen_risk_le_840a93_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['last_incident_date'], name='core_studen_last_in_2523bf_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['academic_status'], name='core_studen_academi_dc3646_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='core_notifi_created_d0c445_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='core_notifi_is_read_127eae_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='core_notifi_notific_cbfe88_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinereport',
            index=models.Index(fields=['reported_at'], name='core_discip_reporte_bcbab5_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinereport',
            index=models.Index(fields=['student', 'reported_at'], name='core_discip_student_e21810_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinereport',
            index=models.Index(fields=['rating'], name='core_discip_rating_425d10_idx'),
        ),
        migrations.AddIndex(
            model_name='disciplinereport',
            index=models.Index(fields=['points'], name='core_discip_points_78588e_idx'),
        ),
    ]
