# Generated by Django 6.1 on 2026-08-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="logged_out_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
