# Generated by Django 5.2.17 on 2026-08-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_add_logged_out_at_to_usersession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disciplinecategory",
            name="key",
            field=models.CharField(
                choices=[
                    ("ATTENDANCE", "Attendance Offenses"),
                    ("ACADEMIC", "Academic Offenses"),
                    ("UNIFORM", "Uniform & Grooming Offenses"),
                    ("CLASSROOM", "Classroom Misconduct"),
                    ("DISRESPECT", "Disrespect & Insubordination"),
                    ("BULLYING", "Bullying & Harassment"),
                    ("FIGHTING", "Fighting & Violence"),
                    ("THEFT", "Theft & Dishonesty"),
                    ("PROPERTY", "School Property Offenses"),
                    ("TECHNOLOGY", "Technology & Phone Misuse"),
                    ("SUBSTANCE", "Substance Abuse Offenses"),
                    ("SEXUAL", "Sexual Misconduct"),
                    ("RELATIONSHIP", "Relationship & Coupling Offenses"),
                    ("SECURITY", "School Security Offenses"),
                    ("MASS_INDISCIPLINE", "Mass Indiscipline"),
                    ("HEALTH_SAFETY", "Health & Safety Violations"),
                    ("COMMUNITY", "Community & Social Misconduct"),
                    ("EXAM", "Examination & Assessment Offenses"),
                    ("LEADERSHIP", "Leadership & Prefect Misconduct"),
                    ("TRANSPORT", "Transport & Travel Offenses"),
                    ("ENVIRONMENT", "Environmental & Sanitation Offenses"),
                    ("CRIMINAL", "Criminal & Legal Offenses"),
                    ("CUSTOM", "Custom Case"),
                ],
                max_length=30,
                unique=True,
            ),
        ),
    ]
