# Generated by Django 5.2.17 on 2026-09-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_disciplinecategory_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacherprofile",
            name="must_reset_password",
            field=models.BooleanField(default=False),
        ),
    ]
